---
- name: Install metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/download/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    # Use command module
  - name: drop in metricbeat config
    copy:
     src: /etc/ansible/roles/files/metricbeat-config.yml
     dest: /etc/metricbeat/metricbeat-config.yml

  - name: enable and configure docker module for metricbeat
    command: sudo metricbeat modules enable docker

  - name: setup metricbeat
    command: sudo metricbeat setup -e

  - name: start metricbeat
    command: sudo service metricbeat start
